labels:
  - name: bug
    color: "d73a4a"
    description: "Something isn’t working"

  - name: enhancement
    color: "a2eeef"
    description: "New feature or improvement"

  - name: help wanted
    color: "008672"
    description: "Extra attention needed"

  - name: documentation
    color: "0075ca"
    description: "Improvements or additions to documentation"

  - name: good first issue
    color: "7057ff"
    description: "Good for newcomers"

  - name: question
    color: "d876e3"
    description: "Further information is requested"

  - name: invalid
    color: "e4e669"
    description: "This doesn’t seem right or needs clarification"

  - name: wontfix
    color: "ffffff"
    description: "This will not be worked on"

  - name: duplicate
    color: "cfd3d7"
    description: "This issue or PR already exists"
